source 'https://github.com/zhengya123/ZYModule.git'
platform :ios, '8.0'

target 'ZYAlertView_Example' do
  pod 'ZYAlertView', :path => '../'
  pod 'ZYImageModule'
  target 'ZYAlertView_Tests' do
    inherit! :search_paths

    
  end
end
